---
version: "3.3"

services:
  main:
    build: .
    ports:
      - "8081:8081"
    environment:
      YTPR_PLAYLIST_LIST: "PLUcjmvZLvmS_vTF8su_eqA6XgCfl88kuV"
      YTPR_HTTP_PORT: 8081
      YTPR_ARCHIVE_FILE: "/downloads/archive.txt"
      YTPR_VIDEO_QUALITY: "height:1080"
    volumes:
      - ./downloads:/downloads
      - ./config:/config
