---
version: "3.3"

services:
  main:
    build: .
    ports:
      - "8080:8080"
    environment:
      YTPR_CRON_STRING: "* * * * *"
      YTPR_PLAYLIST_LIST: "PLUcjmvZLvmS_vTF8su_eqA6XgCfl88kuV"
    volumes:
      - ./downloads:/downloads
      - ./config:/config
